name = "Mice"
uuid = "d4678d24-b338-4f96-a2c8-a66549d61c16"
authors = ["Tom Metherell <thomas.metherell.22@ucl.ac.uk> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.8.5"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
